services:
  - type: web
    name: wethaq
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PIP_DEFAULT_TIMEOUT
        value: 100
    disk:
      name: ledger-data
      mountPath: /data
      sizeGB: 1
